### ISSUE TITLE
Occasionally, an error occurred after setting "WalletTxBuilder".

### ISSUE THREAD

**Issue by Kang-Simon** [bosagora/boa-sdk-ts#291]
When the amount is changed or a New_Block event occurs on the "SendBoa" screen. 
The error occurs intermittently.

<img width="1030" alt="WalletTxBuilder2021-10-28  17 15 17" src="https://user-images.githubusercontent.com/88305621/139353427-66fb4fd4-0805-4a9f-9ebf-358f6f39b982.png">

**Comment by MichaelKim20** [comment]
@Kang-Simon 
I carefully checked the pattern of using Wallet TxBuilder in Wallet.
This is because the account object is shared on two screens.
This will be resolved by initializing all data on the Wallet TxBuilder object used at the end of the screen and deleting the event.
