### ISSUE TITLE
Sometimes another error occurred after setting "WalletTxBuilder".

### ISSUE THREAD

**Issue by Kang-Simon** [bosagora/boa-sdk-ts#293]
New_Block event occurs on the "SendBoa" screen.
The error occurs intermittently.
<img width="1033" alt="WalletTxBuilder_error2 2021-10-29 오전 10 45 34" src="https://user-images.githubusercontent.com/88305621/139375376-28ab6f8c-9464-4350-8b1b-8d081bbdd119.png">

**Comment by MichaelKim20** [comment]
@Kang-Simon 
I carefully checked the pattern of using Wallet TxBuilder in Wallet.
This is because the account object is shared on two screens.
This will be resolved by initializing all data on the Wallet TxBuilder object used at the end of the screen and deleting the event.

**Comment by MichaelKim20** [comment]
In addition, the code for building transactions in the calculation step was removed so that this issue no longer occurred.
