### ISSUE TITLE
It can calculate the byte size of the block.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/boa-sdk-ts#325]
It can only know the byte size of the transaction.
However, providing additional information will help STOA.

**Comment by MichaelKim20** [comment]
https://github.com/bosagora/boa-sdk-ts/blob/v0.x.x/src/modules/data/Block.ts#L98-L108
You can serialize the blocks and use the length of the result.

**Comment by MichaelKim20** [comment]
> https://github.com/bosagora/boa-sdk-ts/blob/v0.x.x/src/modules/data/Block.ts#L98-L108 You can serialize the blocks and use the length of the result.

Looking further, there is a slight difference between the length of the result after serializing and actual size .
