### ISSUE TITLE
Implement the shell function that provides the height and creation time of the last block.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/boa-sdk-ts#37]
- input:
   None
- output:
   height: the height of the last block
   time : Unix approach time
Block data does not yet contain the creation time of the block, so make it a sell function as follows:
height = the height of the last block
time = (new Date("2020-01-01 00:00:00")).getTime() + height * 10 * 60 * 1000

**Comment by TrustHenry** [comment]
This will have to return the ledger timestamp value.

**Comment by MichaelKim20** [comment]
No need for it
